import { app, BrowserWindow, ipcMain, session } from 'electron';
import Parser from 'rss-parser';
import { FeedItem } from './types/FeedItem';
import { ElectronBlocker } from '@ghostery/adblocker-electron';
import fetch from 'cross-fetch';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = () : void => {

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webviewTag: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then( async () => {
  const blocker = await ElectronBlocker.fromPrebuiltAdsAndTracking(fetch);
  blocker.enableBlockingInSession(session.defaultSession);

  blocker.on('request-blocked', (req) => {
    console.log('[BLOCKED]', req.url);
  });

  createWindow();

}).catch( (err) =>{
  console.error( "Failed at startup: ", err );
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

type CustomFeed = {foo: string};
type CustomItem = {'media:thumbnail' : string};

const parser: Parser<CustomFeed, CustomItem> = new Parser({
  customFields: {
    feed: ['foo'],
    item: ['media:thumbnail']
  }
});


ipcMain.handle('get-rss-feed', async () => {
  try {
    const feed = await parser.parseURL('https://news.ycombinator.com/rss');

    let items : FeedItem[] = [];
    feed.items.forEach(i => {
      console.log(i);
      const f : FeedItem = { 'title': i.title, 'link': i.link, 'pubDate': i.pubDate, 'content': i.content, 'media': i['media:thumbnail'] };
      items.push(f);
    });
    return items;

  } catch( err ) {
    console.error(err);
  }
});